[build]
  functions = "functions"
  publish = "public"
  command = "composer install && php artisan optimize && npm install && npm run build && cp -r vendor bootstrap config app public routes functions/ && chmod +x functions/php"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200